export const HANDLE_LOAD_LIST = 'handle_load_list'
export const HANDLE_FILTEREDINFO_CHANGE = 'handle_filteredinfo_change'
export const CLEAR_FILTERS = 'clear_filters'
export const HANDLE_FILTERS = 'handle_filters'
export const HANDLE_ERROR = 'handle_error'
export const CLEAR_ERROR = 'clear_error'