export const LOAD_USER_LIST = 'load_user_list'
export const HANDLE_EMAIL_CHANGE = 'handle_email_change'
export const HANDLE_PASSWORD_CHANGE = 'handle_password_change'
export const RESET_NEW_ADMIN = 'reset_new_admin'
export const SET_ERROR_MSG = 'set_error_msg'